In [ ]:
# Pandas: Effient Python Tool for Loading, Cleaning, Sorting and Filtering Structured Data(Tables-Spreadsheet, SQL)
# Two Data Structures:
# 1. Pandas Series: Single Column Data(One dimentional Data)
# 2. Pandas DataFrame: Multi-Column Data(Two Dimensition Data) -> rows and columns


# PANDAS SERIES 1D
# By Default: Each Data is assigned an index number starting from zero, Also the column name is an index
import pandas as pd
stock_prices = [180, 185, 190, 200, 195, 210, 220]
days =  ["Mon", "Tue", "Wed", "Thur", "Fri", "Sat", "Sun"]

stock_prices_series =  pd.Series(stock_prices, name = "Stock Prices", index = days)
stock_prices_series

Mon     180
Tue     185
Wed     190
Thur    200
Fri     195
Sat     210
Sun     220
Name: Stock Prices, dtype: int64

In [3]:
import pandas as pd

# Creating a Pandas Series
stock_prices = pd.Series([180, 185, 190, 200, 195, 210, 220],
                         index=["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"], name = "Stock Prices")

stock_prices

Mon    180
Tue    185
Wed    190
Thu    200
Fri    195
Sat    210
Sun    220
Name: Stock Prices, dtype: int64

In [4]:
# Properties of Pandas Series
# Series have 4 Properties
# 1. Values -> Information Represented in a Numpy Array
# 2. Index  -> How the information can be Retrieved, By Default index are numerical starting from zero
# 3. Name   -> Represent the name of the Column
# 4. Dtype  -> Datatypes of values stored in a Pandas Series

print(stock_prices.values)
print(type(stock_prices.values))
print(stock_prices.index)
print(stock_prices.name)
print(stock_prices.dtype)

[180 185 190 200 195 210 220]
<class 'numpy.ndarray'>
Index(['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], dtype='object')
Stock Prices
int64

In [5]:
# Common Operations on Pandas Series
# 1. Statistical Operations
max_price = stock_prices.max()
print(max_price)

min_price = stock_prices.min()
print(min_price)

mean_price = stock_prices.mean()
print(mean_price)

median_price = stock_prices.median()
print(median_price)

220
180
197.14285714285714
195.0

In [6]:
# 2. Filtering Operations: Extract Information
# a) Find Days When Stock Price Was Above 190
stock_prices[stock_prices > 190]

Thu    200
Fri    195
Sat    210
Sun    220
Name: Stock Prices, dtype: int64

In [7]:
# b) Apply mathematical Operations

adjusted_prices = stock_prices * 1.10  # Increase by 5%
adjusted_prices

Mon    198.0
Tue    203.5
Wed    209.0
Thu    220.0
Fri    214.5
Sat    231.0
Sun    242.0
Name: Stock Prices, dtype: float64

In [ ]:
# PANDAS DATAFRAME 2D
# Table(rows, columns) for Representing Structured Data
# Multiple Column Data, where each column represent a Pandas Series

# Employee Salary Data

data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 30, 22, 28],
    "Job Role": ["Chef", "Waiter", "Manager", "Cashier"],
    "Salary": [50000, 30000, 70000, 40000]
}

df = pd.DataFrame(data)
df

      Name  Age Job Role  Salary
0    Alice   25     Chef   50000
1      Bob   30   Waiter   30000
2  Charlie   22  Manager   70000
3    David   28  Cashier   40000

In [ ]:
# Properties of a DataFrame
# 1. shape: The number of rows and columns
# 2. size : The total items stored in the array

print(df.shape)
print(df.size)

(4, 4)
16

In [8]:
# Importing DataFrames from Different Sources
# To read data from Different Sources we can use the following functions depending on the data
# 1. Excel -> pd.read_excel(link)
# 2. CSV   -> pd.read_csv(link)
# 3. JSON  -> pd.read_json(link)


data_url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data'
columns = [
    'age', 'workclass', 'fnlwgt', 'education', 'education_num',
    'marital_status', 'occupation', 'relationship', 'ethnicity',
    'gender','capital_gain','capital_loss','hours_per_week',
    'country_of_origin','income'
]

# Loading an external data
data = pd.read_csv(data_url, names = columns)
data

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,ethnicity,gender,capital_gain,capital_loss,hours_per_week,country_of_origin,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [9]:
# Common Operations in Pandas DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 30, 22, 28],
    "Job Role": ["Chef", "Waiter", "Manager", "Cashier"],
    "Salary": [50000, 30000, 70000, 40000]
}

df = pd.DataFrame(data)
df

      Name  Age Job Role  Salary
0    Alice   25     Chef   50000
1      Bob   30   Waiter   30000
2  Charlie   22  Manager   70000
3    David   28  Cashier   40000

In [ ]:
# a) Sorting Employees by Salary
df.sort_values(by = "Salary", ascending=False)

      Name  Age Job Role  Salary
2  Charlie   22  Manager   70000
0    Alice   25     Chef   50000
3    David   28  Cashier   40000
1      Bob   30   Waiter   30000

In [10]:
#  b) Filtering Employees with Salary Above 40,000
df['Salary'] > 40000

df[df['Salary'] > 40000]

      Name  Age Job Role  Salary
0    Alice   25     Chef   50000
2  Charlie   22  Manager   70000

In [11]:
# c)  Calculating Average Salary
df['Salary'].mean()

np.float64(47500.0)

In [ ]:
# d) Adding a new Column
# Adding a New Column for Bonus (10% of Salary)

df['Bonus'] = df['Salary'] * 0.20
df

      Name  Age Job Role  Salary    Bonus
0    Alice   25     Chef   50000  10000.0
1      Bob   30   Waiter   30000   6000.0
2  Charlie   22  Manager   70000  14000.0
3    David   28  Cashier   40000   8000.0

In [12]:
import pandas as pd

climate_data = pd.DataFrame({
    "Year": [2000, 2005, 2010, 2015, 2020],
    "Avg Temperature": [14.3, 14.5, 14.8, 15.1, 15.5]
})

# Calculate the temperature trend
climate_data['Temp Change'] = climate_data["Avg Temperature"].diff()
climate_data

   Year  Avg Temperature  Temp Change
0  2000             14.3          NaN
1  2005             14.5          0.2
2  2010             14.8          0.3
3  2015             15.1          0.3
4  2020             15.5          0.4

In [13]:
sales_data = pd.DataFrame({
    "Product": ["Laptop", "Phone", "Tablet", "Monitor"],
    "Sales": [500, 1200, 300, 700],
    "Revenue": [500000, 900000, 150000, 350000]
})

sales_data

# Find the most profitable product
most_profitable = sales_data[sales_data["Revenue"] == sales_data["Revenue"].max()]
most_profitable

  Product  Sales  Revenue
1   Phone   1200   900000

In [14]:
hospital_data = pd.DataFrame({
    "Hospital": ["A", "B", "C", "D"],
    "Patients": [150, 200, 170, 220],
    "Doctors": [20, 30, 25, 35]
})

# Calculate doctor-to-patient ratio
hospital_data["Doctor-Patient Ratio"] = hospital_data["Patients"] / hospital_data["Doctors"]
hospital_data

  Hospital  Patients  Doctors  Doctor-Patient Ratio
0        A       150       20              7.500000
1        B       200       30              6.666667
2        C       170       25              6.800000
3        D       220       35              6.285714

In [15]:
education_data = pd.DataFrame({
    "School": ["X", "Y", "Z", "W"],
    "Students": [500, 750, 600, 800],
    "Teachers": [40, 50, 45, 55]
})

# Calculate student-to-teacher ratio
education_data["Student-Teacher Ratio"] = education_data["Students"] / education_data["Teachers"]
education_data

  School  Students  Teachers  Student-Teacher Ratio
0      X       500        40              12.500000
1      Y       750        50              15.000000
2      Z       600        45              13.333333
3      W       800        55              14.545455

In [ ]:
transport_data = pd.DataFrame({
    "City": ["New York", "London", "Tokyo", "Paris"],
    "Avg Commute Time (min)": [45, 40, 35, 50],
    "Public Transport Usage (%)": [70, 80, 85, 75]
})

# Find the city with the shortest commute time
best_commute = transport_data[transport_data["Avg Commute Time (min)"] == transport_data["Avg Commute Time (min)"].min()]
best_commute

    City  Avg Commute Time (min)  Public Transport Usage (%)
2  Tokyo                      35                          85